#!/bin/sh

FILE=${1:?"Source file required: ./gdl FILE"}
ROOT=$(echo $FILE | sed 's/\.\w*$//g')

yasm -g dwarf2 -f elf64 -l "$ROOT.lst" -o "$ROOT.o" "$FILE"
gcc -g -no-pie -pthread -lm -o "$ROOT" "$ROOT.o"
