#!/bin/sh

FILE=${1:?"Source file required: ./getenc FILE"}
ROOT=$(echo $FILE | sed 's/\.\w*$//g')

yasm -g dwarf2 -f elf64 -l "$ROOT.lst" -o "$ROOT.o" "$FILE"
awk 'length($4) != 0 {print $4, $5, $6, $7, $8, $9}' < "$ROOT.lst" > "$ROOT.dec"
