#!/bin/sh

FILE=${1:?"Source file required: ./getenc FILE"}
ROOT=$(echo $FILE | sed 's/\.\w*$//g')

yasm -g dwarf2 -f elf64 -l "$ROOT.lst" -o "$ROOT.o" "$FILE"
awk 'length($3) != 0 {print $3}' < "$ROOT.lst" > "$ROOT.enc"
